name: wuchuheng_logger
description: This is a log library for dart.
version: 1.0.5
homepage: https://github.com/wuchuheng/logger_dart

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  stack_trace: ^1.10.0
  wuchuheng_hooks: ^0.0.7
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.0.0
  test: ^1.16.0
