name: wuchuheng_logger
description: This is a log library for dart.
version: 0.0.1
homepage: https://github.com/wuchuheng/logger_dart

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  stack_trace: ^1.10.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
